### ISSUE TITLE
Change Text for last card

### ISSUE THREAD

**Issue by Ssravani272** [petabencana/cognicity-cards-ng#51]

**Comment by ruthvik129** [comment]
@Ssravani272 i have reverted the PR for this issue as the text is changed directly , The text should be rendered conditionally 
i.e 

- If the user selected training at the first then the traning text should be showing up
- Else the previous text should be their

Check line no 184 in en.json or id.json for reference
```
    "submitButton": {
        "real": "Submit Report",
        "training": "Complete Training"
    },
```
You can also see how the submit-button-component is rendering the text based on real or traning report , the same should be replicated in thank-you component
